version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*

# Including the buildSpec's required CodeBuild project configuration
# This section may be edited to specify environment variables and other settings needed.